const params=new URLSearchParams(location.search);let type=params.get('type')||localStorage.getItem('registrationType')||'sports';let currentStep=1;
function setType(){const sports=type==='sports';const e=document.getElementById('typeEyebrow');if(!e)return;e.textContent=sports?'SPORTS REGISTRATION':'CULTURAL REGISTRATION';document.getElementById('formTitle').textContent=sports?'Sports Registration':'Cultural Registration';document.getElementById('sportsFields').classList.toggle('hidden',!sports);document.getElementById('culturalFields').classList.toggle('hidden',sports);localStorage.setItem('registrationType',type);updateProgress(1)}
function updateProgress(n){const hints=['Student details','School / college','Your talent','Review & submit'];const no=document.getElementById('stepNo');const hint=document.getElementById('progressHint');if(no)no.textContent=n;if(hint)hint.textContent=hints[n-1];document.querySelectorAll('.progress span').forEach((x,i)=>x.classList.toggle('active',i<n))}
function showStep(n){currentStep=n;for(let i=1;i<=4;i++)document.getElementById('step'+i)?.classList.toggle('hidden',i!==n);updateProgress(n);window.scrollTo({top:0,behavior:'smooth'})}
function nextStep(n){if(n===1){if(!val(['name','dob','gender','mobile']))return;if(!/^\d{10}$/.test(document.getElementById('mobile').value))return alert('Please enter a valid 10-digit mobile number.')}if(n===2&&!val(['district','block','school','className']))return;if(n===3){if((type==='sports'&&!val(['sport']))||(type==='cultural'&&!val(['cultural'])))return;buildPreview()}showStep(n+1)}
function val(ids){for(const id of ids){const x=document.getElementById(id);if(!x.value.trim()){x.focus();alert('Please complete all required fields.');return false}}return true}
function buildPreview(){const d=getData();const rows=[['Name',d.name],['Date of Birth',d.dob],['Gender',d.gender],['Mobile',d.mobile],['District',d.district],['Block / City',d.block],['School / College',d.school],['Class / Course',d.className],['Registration Type',type==='sports'?'Sports':'Cultural'],['Activity',d.activity],['Achievements',d.achievement||'Not provided']];document.getElementById('preview').innerHTML=rows.map(r=>`<div><span>${r[0]}</span><b>${escapeHtml(r[1])}</b></div>`).join('')}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function getData(){return{name:document.getElementById('name').value.trim(),dob:document.getElementById('dob').value,gender:document.getElementById('gender').value,mobile:document.getElementById('mobile').value.trim(),district:document.getElementById('district').value,block:document.getElementById('block').value.trim(),school:document.getElementById('school').value.trim(),className:document.getElementById('className').value.trim(),activity:type==='sports'?document.getElementById('sport').value:document.getElementById('cultural').value,achievement:document.getElementById('achievement').value.trim()}}
function submitRegistration(){if(!document.getElementById('declaration').checked)return alert('Please accept the declaration.');const d=getData();const reg='BSTR26-'+String(Date.now()).slice(-6);const user={...d,type,reg};localStorage.setItem('student_'+d.mobile,JSON.stringify(user));localStorage.setItem('currentStudent',d.mobile);alert(`Registration successful!\n\nRegistration ID: ${reg}\nUser ID: ${d.mobile}\nInitial password: your DOB`);location.href='dashboard.html'}
function login(){const m=document.getElementById('loginMobile').value.trim(),dob=document.getElementById('loginDob').value;const u=JSON.parse(localStorage.getItem('student_'+m)||'null');if(!u||u.dob!==dob){document.getElementById('loginError').textContent='Invalid User ID or password. Please check your mobile number and DOB.';return}localStorage.setItem('currentStudent',m);location.href='dashboard.html'}
function loadDashboard(){const m=localStorage.getItem('currentStudent'),u=JSON.parse(localStorage.getItem('student_'+m)||'null');if(!u){location.href='login.html';return}document.getElementById('dashName').textContent=u.name;document.getElementById('profileName').textContent=u.name;document.getElementById('regId').textContent=u.reg;document.getElementById('dashType').textContent=u.type==='sports'?'Sports':'Cultural';document.getElementById('dashActivity').textContent=u.activity;document.getElementById('dashDistrict').textContent=u.district;document.getElementById('dashMobile').textContent=u.mobile;document.getElementById('dashSchool').textContent=u.school;document.getElementById('dashClass').textContent=u.className}
function logout(){localStorage.removeItem('currentStudent');location.href='login.html'}
if(document.getElementById('formTitle'))setType();
